"use client";

import React, { createContext, useContext, useState } from "react";

export interface BusinessData {
  id: number;
  name: string;
  email: string;
  website: string;
  phone?: string;
}

interface BusinessesContextType {
  businesses: BusinessData[];
  setBusinesses: React.Dispatch<React.SetStateAction<BusinessData[]>>;
  isPending: boolean;
  setIsPending: React.Dispatch<React.SetStateAction<boolean>>;
}

const BusinessesContext = createContext<BusinessesContextType | undefined>(
  undefined
);

export const BusinessesProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [businesses, setBusinesses] = useState<BusinessData[]>([
    {
      name: "ARAC Roof It Forward",
      website: "roofitforwardin.com",
      phone: "(317) 975-1176",
      email: "",
      id: 1,
    },
    {
      name: "Rojas Roofing",
      website: "rojasroofing.com",
      phone: "(317) 747-3498",
      email: "Freddy@RojasRoofing.com",
      id: 2,
    },
    {
      name: "Rojas Roofing",
      website: "rojasroofing.com",
      phone: "(317) 747-3498",
      email: "christian@RojasRoofing.com",
      id: 3,
    },
    {
      name: "Rojas Roofing",
      website: "rojasroofing.com",
      phone: "(317) 747-3498",
      email: "Patrick@RojasRoofing.com",
      id: 4,
    },
    {
      name: "Bone Dry Roofing",
      website: "bonedry.com",
      phone: "(463) 251-7473",
      email: "recruiting@bonedry.com",
      id: 5,
    },
    {
      name: "Rhino Roofing & Exteriors",
      website: "rhinoroofingext.com",
      phone: "(317) 699-5715",
      email: "",
      id: 6,
    },
    {
      name: "Stay Dry Roofing Noblesville",
      website: "staydryroofing.com",
      phone: "(317) 214-6358",
      email: "info@staydryroofing.com",
      id: 7,
    },
    {
      name: "Cloud Nine Roofing and Renovation",
      website: "callcloudnine.com",
      phone: "(317) 900-4262",
      email: "info@callcloudnine.com",
      id: 8,
    },
    {
      name: "Cloud Nine Roofing and Renovation",
      website: "callcloudnine.com",
      phone: "(317) 900-4262",
      email: "INFO@CALLCLOUDNINE.COM",
      id: 9,
    },
    {
      name: "Cloud Nine Roofing and Renovation",
      website: "callcloudnine.com",
      phone: "(317) 900-4262",
      email: "8c4075d5481d476e945486754f783364@sentry.io",
      id: 10,
    },
    {
      name: "SOS Roofing and Construction LLC",
      website: "callsosroofing.com",
      phone: "(317) 918-0938",
      email: "sales@sosroofingandconstruction.com",
      id: 11,
    },
    {
      name: "SOS Roofing and Construction LLC",
      website: "callsosroofing.com",
      phone: "(317) 918-0938",
      email: "8c4075d5481d476e945486754f783364@sentry.io",
      id: 12,
    },
    {
      name: "Ameriserve LLC",
      website: "myameriserve.com",
      phone: "(317) 777-0267",
      email: "",
      id: 13,
    },
    {
      name: "3 Kings Roofing and Construction",
      website: "3kingsroofingandgutters.com",
      phone: "(317) 900-4336",
      email: "info@3kingsroofingandgutters.com",
      id: 14,
    },
    {
      name: "3 Kings Roofing and Construction",
      website: "3kingsroofingandgutters.com",
      phone: "(317) 900-4336",
      email: "paul@3KingsConstruction.net",
      id: 15,
    },
    {
      name: "Taylor Home Improvement",
      website: "taylorhomeimprovement.net",
      phone: "(317) 523-7186",
      email: "info@taylorhomeimprovement.net",
      id: 16,
    },
    {
      name: "Taylor Home Improvement",
      website: "taylorhomeimprovement.net",
      phone: "(317) 523-7186",
      email: "hello@taylorhomeimprovement.net",
      id: 17,
    },
    {
      name: "Blend N Roofing",
      website: "blendnroofing.com",
      phone: "(317) 284-1965",
      email: "info@blendn.com",
      id: 18,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "Buckner@tectaamerica.com",
      id: 19,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "sbuckner@tectaamerica.com",
      id: 20,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jsmith@tectaamerica.com",
      id: 21,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jwilson@tectaamerica.com",
      id: 22,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "mcole@tectaamerica.com",
      id: 23,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "rgauldin@tectaamerica.com",
      id: 24,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "lbuckner@tectaamerica.com",
      id: 25,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "arodriguez3@tectaamerica.com",
      id: 26,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "klogan@tectaamerica.com",
      id: 27,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "mtyler@tectaamerica.com",
      id: 28,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "dlarsen@tectaamerica.com",
      id: 29,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "smahoney@tectaamerica.com",
      id: 30,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "zbuckner@tectaamerica.com",
      id: 31,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "Info@Tectaamerica.com",
      id: 32,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@tectaamerica.com",
      id: 33,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "acarr@tectaamerica.com",
      id: 34,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "Info_ABC_Roofing@tectaamerica.com",
      id: 35,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "dthompson02@tectaamerica.com",
      id: 36,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "anthonyroofingestimating@tectaamerica.com",
      id: 37,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jziebarth@tectaamerica.com",
      id: 38,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "bladmin@tectaamerica.com",
      id: 39,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "sagnew@tectaamerica.com",
      id: 40,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "mhall@tectaamerica.com",
      id: 41,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@chrisandersenroofing.com",
      id: 42,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "ryan@christiansonroofing.com",
      id: 43,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "commercialroofing@tectaamerica.com",
      id: 44,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "dsoccio@tectaamerica.com",
      id: 45,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "pmckellar@tectaamerica.com",
      id: 46,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "dstefko@tectaamerica.com",
      id: 47,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@empireroofing.com",
      id: 48,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@christiansenroofing.com",
      id: 49,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@fortwayneroofing.com",
      id: 50,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jpierce2@tectaamerica.com",
      id: 51,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@jppatti.com",
      id: 52,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "service.jbroofing@tectaamerica.com",
      id: 53,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "Service.JBRoofing@tectaamerica.com",
      id: 54,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "mctaadmin@tectaamerica.com",
      id: 55,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "bhauschildt@tectaamerica.com",
      id: 56,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "rgilbreath@tectaamerica.com",
      id: 57,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "mail@oshkoshindustrial.com",
      id: 58,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "ralph@roofservices.com",
      id: 59,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jvieni@tectaamerica.com",
      id: 60,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "aschuyler@tectaamerica.com",
      id: 61,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.rsm@tectaamerica.com",
      id: 62,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "kbullock@tectaamerica.com",
      id: 63,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jlauberth@tectaamerica.com",
      id: 64,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.mankato@tectaamerica.com",
      id: 65,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "thonea@tectaamerica.com",
      id: 66,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.arizona@tectaamerica.com",
      id: 67,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.charlotte@tectaamerica.com",
      id: 68,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info-den@tectaamerica.com",
      id: 69,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jweems@tectaamerica.com",
      id: 70,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.mandan@tectaamerica.com",
      id: 71,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.devilslake@tectaamerica.com",
      id: 72,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.fargo@tectaamerica.com",
      id: 73,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.grand-forks@tectaamerica.com",
      id: 74,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.jamestown@tectaamerica.com",
      id: 75,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.minot@tectaamerica.com",
      id: 76,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.baltimore@tectaamerica.com",
      id: 77,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.fruitland@tectaamerica.com",
      id: 78,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "chmummert@tectaamerica.com",
      id: 79,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.jessup@tectaamerica.com",
      id: 80,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "bmcclelland@tectaamerica.com",
      id: 81,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.illinois@tectaamerica.com",
      id: 82,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.belleville@tectaamerica.com",
      id: 83,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jdonovan@tectaamerica.com",
      id: 84,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "dlaymon@tectaamerica.com",
      id: 85,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.sacramento@tectaamerica.com",
      id: 86,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.seattle@tectaamerica.com",
      id: 87,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@deerfieldbeach.com",
      id: 88,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "service.atlanta@tectaamerica.com",
      id: 89,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.birmingham@tectaamerica.com",
      id: 90,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.orlando@tectaamerica.com",
      id: 91,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.los-angeles@tectaamerica.com",
      id: 92,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jboyd@tectaamerica.com",
      id: 93,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.tampa@tectaamerica.com",
      id: 94,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.columbus@tectaamerica.com",
      id: 95,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.cincinnati@tectaamerica.com",
      id: 96,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info.dayton@tectaamerica.com",
      id: 97,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "rtherrien@tectaamerica.com",
      id: 98,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@tmrroofing.net",
      id: 99,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "info@westroof.com",
      id: 100,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "wolferoofing@wrsm.net",
      id: 101,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "jmassarelli@tectaamerica.com",
      id: 102,
    },
    {
      name: "Blackmore & Buckner Roofing, a Tecta America Company LLC",
      website: "tectaamerica.com",
      phone: "(317) 263-0707",
      email: "service@tectaamerica.com",
      id: 103,
    },
    {
      name: "Weathertight Roofing",
      website: "weathertightroofingllc.com",
      phone: "(317) 983-7663",
      email: "info@weathertightroofingllc.com",
      id: 104,
    },
    {
      name: "Weathertight Roofing",
      website: "weathertightroofingllc.com",
      phone: "(317) 983-7663",
      email: "agrim@weathertightroofingllc.com",
      id: 105,
    },
    {
      name: "Blue Ladder Roofing",
      website: "blueladderroofs.com",
      phone: "(317) 458-2886",
      email: "",
      id: 106,
    },
    {
      name: "Capital Pro Roofing",
      website: "capitalproroofing.com",
      phone: "(317) 210-2254",
      email: "",
      id: 107,
    },
    {
      name: "Ridgeline General Contractors",
      website: "ridgelinegc.net",
      phone: "(317) 967-3539",
      email: "info@ridgelinegc.net",
      id: 108,
    },
    {
      name: "Reed Roofing, LLC",
      website: "roofsbyreed.com",
      phone: "(877) 445-7333",
      email: "",
      id: 109,
    },
    {
      name: "American Pyramids Roofing",
      website: "pyramids-roofing.com",
      phone: "(317) 827-5303",
      email: "pyramids.roofing@gmail.com",
      id: 110,
    },
    {
      name: "BH Pro Roofing",
      website: "bhproconstruction.com",
      phone: "(317) 220-2450",
      email: "",
      id: 111,
    },
  ]);
  const [isPending, setIsPending] = useState(false);

  return (
    <BusinessesContext.Provider
      value={{ businesses, setBusinesses, isPending, setIsPending }}
    >
      {children}
    </BusinessesContext.Provider>
  );
};

export const useBusinesses = () => {
  const context = useContext(BusinessesContext);
  if (!context) {
    throw new Error("useBusinesses must be used within a BusinessesProvider");
  }
  return context;
};
